### ISSUE TITLE
你的jar包有问题

### ISSUE THREAD

**Issue by lhp15575865420** [yuyashuai/SilkyAnimation#11]
Android studio导入这个jar，用不了。经排查，问题在jar包

**Comment by yuyashuai** [comment]
能详细说下吗，贴下log

**Comment by lhp15575865420** [comment]
是这样的。我导入你的jar后，然后用不了SilkyAnimation这个类。可能是你没打包好，我的Android studio是3.15版本

**Comment by yuyashuai** [comment]
嗯嗯，jar包是有问题的，谢谢反馈。

**Comment by lhp15575865420** [comment]
不客气。我直接那楼主java用了，哈哈。
