### ISSUE TITLE
动画文件都顺序是乱都

### ISSUE THREAD

**Issue by junixapp** [yuyashuai/SilkyAnimation#12]

**Comment by yuyashuai** [comment]
贴下文件？

**Comment by junixapp** [comment]
我看源码中并没有保证动画顺序的机制，只根据文件顺序不可靠

**Comment by yuyashuai** [comment]
默认通过[Collections.sort(List<T> list)](https://developer.android.com/reference/java/util/Collections#sort(java.util.List%3CT%3E))默认排序，只要文件名符合规律，排序就是可靠的。 
要保证**文件名长度**一直，正确的命名方式应该是01,02,03...10,11,12...20,21,22。 
不应该是1,2,3...10,11,12...20,21,22这种排序后将会变成1,10,11..2,20,21,22...3,30,31,32。
