### ISSUE TITLE
切换动画 不会卡顿 也不会透明

### ISSUE THREAD

**Issue by ming838395826** [yuyashuai/SilkyAnimation#13]
你好 我想用你这个做成切换图片不会卡顿 也不是透明 就是直接切换另一个帧动画 这得如果调用 或者说改动

**Comment by yuyashuai** [comment]
现在的切换动画是有预缓存的一个过程，所以中间会卡顿。直接切换需要在播放上一个动画的结尾，提前缓存下一个动画的帧。
