### ISSUE TITLE
hi,问下两个帧动画连续播放切换的话怎么做到无缝切换呢？会有闪屏现象

### ISSUE THREAD

**Issue by fanturbo** [yuyashuai/SilkyAnimation#23]

**Comment by yuyashuai** [comment]
闪屏是指中间出现空白吗？切换动画前调用 `stopAnimation()`了吗？不调用此方法，直接调用 `playAnimaiton()`切换应该是不会出现闪屏的。

**Comment by fanturbo** [comment]
我原先是用的两个控件播放两段动画，会有闪屏现象；现在是在同一个FrameAnimationView控件上播放两段动画，我是在onAnimationEnd方法结束之后直接再次调用playAnimationFromAssets播放的第二段动画，DefaultBitmapPool.kt:142会报空指针，具体应该怎么做呢？如果方便的话可以加下qq吗？615951217，thanks

**Comment by yuyashuai** [comment]
ok
