### ISSUE TITLE
新建一个Demo工程，引入项目出错

### ISSUE THREAD

**Issue by pys200603027** [yuyashuai/SilkyAnimation#25]
报错如下：

```java
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.

```

尝试按照建议也无法解决，貌似是AndroidX包的引入冲突问题

**Comment by pys200603027** [comment]
查阅了下stackoverflow的答案

> The issue is happening because some of your libraries are using androidx components, please try to use a lower version, and make sure that you don't put + while adding dependencies



[stackoverflow](https://stackoverflow.com/questions/55422356/manifest-merger-failed-attribute-applicationappcomponentfactory-android-supp)

**Comment by yuyashuai** [comment]
已更新，请重新引入 ` implementation 'com.yuyashuai.frameanimation:frameanimation:2.0.7`

**Comment by pys200603027** [comment]
感谢作者
