### ISSUE TITLE
设置播放时间的问题！

### ISSUE THREAD

**Issue by DevXue** [yuyashuai/SilkyAnimation#3]
我首先在6.0的小米手机上试了下效果，挺好的，  但是播放时间有点慢，  我修改成了setFrameInterval（50，30,10）之后  然后播放一遍就卡死了，  log控制台总是不停地打印这句话  如下图

![open](https://user-images.githubusercontent.com/9455329/33249860-d76aef72-d367-11e7-9a74-a9704b4966b6.png)
然后我试着把SurfaceViewAnimation类中的 private int mFrameInterval = 100;  这个值给改为 50 ，30  10  也是不行，  控制台同样打印这句话
还有我用Android 4.4的手机跑了一下demo    代码没有任何改动  直接就打印这个log了  界面卡死了 不动弹了！  希望博主看看这个问题  谢谢。

**Comment by yuyashuai** [comment]
关于log的问题我刚更新了下，你更新一下看下，log的日志，或者你方便把你的帧动画发给我吗。你一帧的大小大概是多少kb，我觉得这个应该是间隔过低时候，图片过大缓存的速度跟不上的问题，确认的话我会尽快解决。

**Comment by DevXue** [comment]
Log的问题不存在了，  但是4.4的手机上没有反应！，   我加你QQ咋样，我把代码发你？  
谢谢  或者我的  897902334

**Comment by yuyashuai** [comment]
如果在onCreate中直接调用，请添加一个时延。 
```
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                silkyAnimation.start();
            }
        }, 40);
```
