### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 474246820** [yuyashuai/SilkyAnimation#31]
Tecent-Bugly:上报的日志，请帮忙看看修复一下，谢谢大佬
1 #00 pc 001ea248 /system/lib/libskia.so (SkGpuDevice::~SkGpuDevice()+75) [armeabi-v7a]
--
2 #01 pc 001ebcb0 /system/lib/libskia.so (SkARGB32_Shader_Blitter::blitRect(int, int, int, int)+1936) [armeabi-v7a]
3 java:
4 android.graphics.Canvas.drawBitmap(Canvas.java:1500)
5 com.yuyashuai.frameanimation.drawer.TextureBitmapDrawer.draw(TextureBitmapDrawer.kt:22)
6 com.yuyashuai.frameanimation.FrameAnimation$draw$1.invoke(FrameAnimation.kt:254)
7 com.yuyashuai.frameanimation.FrameAnimation$draw$1.invoke(FrameAnimation.kt:25)
8 kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by yuyashuai** [comment]
#34
