### ISSUE TITLE
我想给你提一个功能PR

### ISSUE THREAD

**Issue by qianshui423** [yuyashuai/SilkyAnimation#35]
支持外部控制播放指定帧功能

**Comment by yuyashuai** [comment]
抱歉，最艰难没有即时查看Gmail邮件。
目前的播放策略是基于[RepeatStrategy](https://github.com/yuyashuai/FrameAnimation/blob/master/frameanimation/src/main/java/com/yuyashuai/frameanimation/repeatmode/RepeatStrategy.kt)，但是使用体验还是不太友好。所以有考虑后面加入`setMinFrame()`  `setMaxFrame()` 等方法。如果能提PR的话最好不过啦~
