### ISSUE TITLE
比较占内存

### ISSUE THREAD

**Issue by yezihengok** [yuyashuai/SilkyAnimation#37]
初次使用体验确实很好 。但我关闭界面在 反复多次进入界面后播放动画 使用内存会一路累加 。。直至APP卡死（页面关闭时onDestroy  里有调用stopAnimation）

**Comment by yuyashuai** [comment]
谢谢反馈~ 正常来说不调用`stopAnimation`，动画资源也会随着View的生命周期进行释放。
如果方便的话请使用`MemoryProfiler`的heapdump在多次重复进入后分析下内存泄露。

**Comment by yuyashuai** [comment]
针对这个case我也会回归下。
