### ISSUE TITLE
frameanimation:2.3.1  新bug

### ISSUE THREAD

**Issue by 474246820** [yuyashuai/SilkyAnimation#38]
java.lang.NullPointerException
03-20 14:59:51.700  9058 17550 E AndroidRuntime: 	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1019)
03-20 14:59:51.700  9058 17550 E AndroidRuntime: 	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1014)
03-20 14:59:51.700  9058 17550 E AndroidRuntime: 	at com.yuyashuai.frameanimation.io.DefaultBitmapPool$decodeBitmap$$inlined$repeat$lambda$1.run(DefaultBitmapPool.kt:138)
03-20 14:59:51.700  9058 17550 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-20 14:59:51.700  9058 17550 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by yuyashuai** [comment]
`DefaultBitmapPool`这个类已经被替换了，这个应该不是2.3.1中的crash，不过能描述下复现的步骤吗。

**Comment by 474246820** [comment]
> `DefaultBitmapPool`这个类已经被替换了，这个应该不是2.3.1中的crash，不过能描述下复现的步骤吗。

是用的2.3.1浮现出来的哦，具体的话应该是销毁了activity，又重新创建了activity，然后测试抓到的，要不你留个联系方式给我吧，方便交流

**Comment by yuyashuai** [comment]
嗯 加Q吧843630100
