### ISSUE TITLE
can't start animation after release这个错误该怎么解决frameanimation:2.3.1

### ISSUE THREAD

**Issue by 474246820** [yuyashuai/SilkyAnimation#39]
03-23 15:04:10.792 18340 18340 E AndroidRuntime: java.lang.IllegalStateException: can't start animation after release
03-23 15:04:10.793 18340 18340 E uncaughtException: can't start animation after releasecom.yuyashuai.frameanimation.io.BitmapPoolImpl.start(BitmapPoolImpl.kt:92)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.yuyashuai.frameanimation.FrameAnimation.playAnimation(FrameAnimation.kt:220)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.yuyashuai.frameanimation.FrameAnimationView.playAnimation(Unknown Source:7)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.qingshu520.chat.modules.chatroom.widget.RoomNobleInView.setAnimationData(RoomNobleInView.java:324)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.qingshu520.chat.modules.chatroom.widget.RoomNobleInView.access$400(RoomNobleInView.java:44)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.qingshu520.chat.modules.chatroom.widget.RoomNobleInView$2.downloadSuccess(RoomNobleInView.java:301)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.qingshu520.chat.modules.chatroom.helper.ZipHelper$1$1.onPostExecute(ZipHelper.java:107)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.qingshu520.chat.modules.chatroom.helper.ZipHelper$1$1.onPostExecute(ZipHelper.java:93)
03-23 15:04:10.793 18340 18340 E uncaughtException: android.os.AsyncTask.finish(AsyncTask.java:695)
03-23 15:04:10.793 18340 18340 E uncaughtException: android.os.AsyncTask.access$600(AsyncTask.java:180)
03-23 15:04:10.793 18340 18340 E uncaughtException: android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
03-23 15:04:10.793 18340 18340 E uncaughtException: android.os.Handler.dispatchMessage(Handler.java:106)
03-23 15:04:10.793 18340 18340 E uncaughtException: android.os.Looper.loop(Looper.java:224)
03-23 15:04:10.793 18340 18340 E uncaughtException: android.app.ActivityThread.main(ActivityThread.java:7060)
03-23 15:04:10.793 18340 18340 E uncaughtException: java.lang.reflect.Method.invoke(Native Method)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
03-23 15:04:10.793 18340 18340 E uncaughtException: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

**Comment by yuyashuai** [comment]
谢谢反馈~ 能说下复现的过程吗, 有手动调用`animationView.release()`方法吗。

**Comment by 474246820** [comment]
> 谢谢反馈~ 能说下复现的过程吗, 有手动调用`animationView.release()`方法吗。

没有调用过，只有动画结束和销毁的时候调用了stopAnimation

**Comment by yuyashuai** [comment]
是在`popupWindow`或`Dialog`中播放动画的吗
