### ISSUE TITLE
java.lang.InterruptedException导致动画提前结束

### ISSUE THREAD

**Issue by hxmars** [yuyashuai/SilkyAnimation#40]
dispatcherThread = thread(start = true, name = "FA-DispatcherThread") {
            try {
                while (state == WORKING && !Thread.currentThread().isInterrupted) {
                    decodeBitmap()
                }
            } catch (e: InterruptedException) {
                Log.e("test", "BitmapPoolImp  error=" + e.toString());
                //java.lang.InterruptedException这里会有异常，导致动画提前结束
                Thread.currentThread().interrupt()
            }
            clearAndStop()
        }

**Comment by yuyashuai** [comment]
`2.3.5`已更新
